from pydantic import BaseModel,EmailStr
from typing import Optional
from datetime import datetime


class TokenData(BaseModel):
    id: Optional[int]= None


class NewUser(BaseModel):
    # A user registeration payload should never contain these fields(id and created_at)!
    #  The id is auto-generated by PostgreSQL, and the created_at timestamp is set 
    # by the database server clock (server_default=text('now()')). Leaving them here 
    # allows malicious users to pass arbitrary numbers into your ID column, causing primary key conflicts.
    # id: Optional[int] = None 
    username: str
    email: EmailStr
    password: str
    # created_at : Optional[datetime] = None
    

class UserResponse(BaseModel):
    id: Optional[int] = None 
    username: str
    email: EmailStr
    created_at : Optional[datetime] = None
    model_config = {"from_attributes": True}
   

class LogInUser(BaseModel):
    email: EmailStr 
    password: str


       