"""make password nullable and add google_id

Revision ID: 78930241878c
Revises: 722732ddbe75
Create Date: 2026-09-10 10:11:12.920640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78930241878c'
down_revision: Union[str, None] = '722732ddbe75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('socialUsers', sa.Column('google_id', sa.String(), nullable=True))
    op.alter_column('socialUsers', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'socialUsers', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'socialUsers', type_='unique')
    op.alter_column('socialUsers', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('socialUsers', 'google_id')
    # ### end Alembic commands ###
